---
# Set the system_domain from helm command line
kube:
  storage_class: nfs-client

system_domain: cap.suse.lab

credentials:
  cf_admin_password: linux
  uaa_admin_client_secret: linux

features:
  eirini:
    enabled: true
  autoscaler:
    enabled: true
  embedded_database:
    enabled: true
  ingress:
    enabled: true
    annotations:
      # cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    tls:
      crt: |
        -----BEGIN CERTIFICATE-----
        MIIF8jCCA9qgAwIBAgIUGKfKxS1BjEmhVR+oIS2bJAu0Q5QwDQYJKoZIhvcNAQEL
        BQAwgYwxCzAJBgNVBAYTAkhLMRIwEAYDVQQIDAlIb25nIEtvbmcxEjAQBgNVBAcM
        CUhvbmcgS29uZzENMAsGA1UECgwEU1VTRTEMMAoGA1UECwwDY2FwMRUwEwYDVQQD
        DAxjYXAuc3VzZS5sYWIxITAfBgkqhkiG9w0BCQEWEmFkbWluQGNhcC5zdXNlLmxh
        YjAeFw0yMDEwMTQxNjAxMDhaFw0yMTEwMTQxNjAxMDhaMIGMMQswCQYDVQQGEwJI
        SzESMBAGA1UECAwJSG9uZyBLb25nMRIwEAYDVQQHDAlIb25nIEtvbmcxDTALBgNV
        BAoMBFNVU0UxDDAKBgNVBAsMA2NhcDEVMBMGA1UEAwwMY2FwLnN1c2UubGFiMSEw
        HwYJKoZIhvcNAQkBFhJhZG1pbkBjYXAuc3VzZS5sYWIwggIiMA0GCSqGSIb3DQEB
        AQUAA4ICDwAwggIKAoICAQDWA5ERuNVOxW2TK+PxwWp/nNyfhRC49NtOWsdN7SO0
        TmoFgjAbnUwnNQ2DH7ETgt7euVTGb8/01fgvJSRpvV9SI14pGRbTPnPDvZTGDqBe
        1WZ67GgyGVFKfOx5BD1eqC4Lmii0yGS3pPImcWDjtglgIRZytRkkbNyuvAyvxaio
        bKRZhOA4VwXXBh9XVDHQC7Z7gHY4t/W+UG0t5cVRPTx3E307oFI4S2z9nvXz2fLC
        KAd3NR6peifwSzT68N8zkZuk4QOm+++CoFNRNBss9gR2QZy4KMVP9FE43NsX5y98
        hW4a/Kt/lX9Lc/kISUX9EewvhVeEr71G3Cn32RbUS7E53PskYrk1SqqXyWIY8YX+
        hisbher5DU1VmMlNxZoGmn6NI5VcVmk9OrjHPAe4/i5g/mncnbaUWawZrOadtN2U
        Gw5Aef3ljLk78KaU4j1gSQktgjiFjo/uliKHijhxYMt1j7SdptV8frfqWdcD1Idw
        cv7ty6VAWtuAl/0P8yDiOFRvlJYRLnPMi5/HVH58cq3WV1TKfNOfUkoUfdALe9Wv
        xVFiypWa7uaT29Y8LMl/oREdfIKuXY0iPpn9xf4nWn+476I2DB0Mf+LFrjdx5z94
        N0v2mGVGVbMYn/Ud42iAYj0NAG50USryNUruMh1w6dt4FuppPyXSxC4353/I9A35
        rwIDAQABo0owSDAJBgNVHRMEAjAAMAsGA1UdDwQEAwIF4DATBgNVHSUEDDAKBggr
        BgEFBQcDATAZBgNVHREEEjAQgg4qLmNhcC5zdXNlLmxhYjANBgkqhkiG9w0BAQsF
        AAOCAgEAFtIF1GXErVs7RR6/XN7kpt8jcKZkb/XKIpLPt2vRIvosmpWo/HvRZ/Ng
        mDBLxesL5TbHWTrF6ICSvUQKSK6jM5VLS6VC0yG9uzPD2+j2AXpJIDaoW6oHJh2t
        jB6gecohWgeTMzeRKnwv5BcTvNkMjPOKKLkxUMJAWLTTqf6y09TpMzA3TzGdMJaN
        uC9zXu07qfeYBRQQAiJefsoh4GmEi4DohFwCKCLMfzQQ6EiprC1JEJSqT152ltGg
        Z8iGuRnzj14MRJDgpEPXRXmzCaEQBHDE8WD4ICFKfGTGYg/YEQq3TpwafJqqqjsF
        pV2ZUE7ZFNbpoOzR//JqnTyab6YrZhwlFeVX7PTFY56WaUq1VMoLI68E2TBJa1Xc
        wdcSChj2axH3H4X/BfmrNYSu3KdLxoEUJ9vnNzqjteCaN6x04cCeLaMJT64NDIF8
        hYauO6MWjBZUJcadOyNYGRtRU3RKt1AaspssO+1tAbF3nO4w0FFq3qDz89LtWLYy
        a/L1tXLyLrh71FwMhcO+1itUvDMZZjkq/tLNgzICnUVdt5JLt6Nfp28lp4NL20jq
        /tr87tcPyjV8KyYXj5DY25PTKg0IvlKR3wtpRlhIKsPhqVLcwOW9ueaA+sLWyFch
        qYiVVBVU7vGcwvno7gbjBCkQwa0h5mkNIoBexL9F9Vgc1HxmwOs=
        -----END CERTIFICATE-----
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQDWA5ERuNVOxW2T
        K+PxwWp/nNyfhRC49NtOWsdN7SO0TmoFgjAbnUwnNQ2DH7ETgt7euVTGb8/01fgv
        JSRpvV9SI14pGRbTPnPDvZTGDqBe1WZ67GgyGVFKfOx5BD1eqC4Lmii0yGS3pPIm
        cWDjtglgIRZytRkkbNyuvAyvxaiobKRZhOA4VwXXBh9XVDHQC7Z7gHY4t/W+UG0t
        5cVRPTx3E307oFI4S2z9nvXz2fLCKAd3NR6peifwSzT68N8zkZuk4QOm+++CoFNR
        NBss9gR2QZy4KMVP9FE43NsX5y98hW4a/Kt/lX9Lc/kISUX9EewvhVeEr71G3Cn3
        2RbUS7E53PskYrk1SqqXyWIY8YX+hisbher5DU1VmMlNxZoGmn6NI5VcVmk9OrjH
        PAe4/i5g/mncnbaUWawZrOadtN2UGw5Aef3ljLk78KaU4j1gSQktgjiFjo/uliKH
        ijhxYMt1j7SdptV8frfqWdcD1Idwcv7ty6VAWtuAl/0P8yDiOFRvlJYRLnPMi5/H
        VH58cq3WV1TKfNOfUkoUfdALe9WvxVFiypWa7uaT29Y8LMl/oREdfIKuXY0iPpn9
        xf4nWn+476I2DB0Mf+LFrjdx5z94N0v2mGVGVbMYn/Ud42iAYj0NAG50USryNUru
        Mh1w6dt4FuppPyXSxC4353/I9A35rwIDAQABAoICABbBGlOAC23sn9HeAMZbgi8/
        RlXPmA+SOR8Dl905MWqiS7N6PBMzjj087sraO8GPUJLtsY3HpZyqg1C/6jcz40ag
        bAqCmGKtaTGOnprQQ0zR86tuJ0XsWzBIR/w17zB5QSwKn/lYtRyxdO2RcHPFjwmh
        evmHN70ftfb+F3s40M3Xf0HlVtGmrwBFrl9inEk6dZR7/BXbuU0a0ADpRSl2EU+3
        ysDkMtm5a0Ur+YqLybvK9cA+7ZunWUe7N07W/WRGPv4wzmqarsR8t18S4zDMl3zb
        TQZnj1MI7vnUwZaxBeN/bE2CP9m402f6VKgE4mQd27bRvpRk+wLltbCcbEj2I0mJ
        5q3346fYRRkNibw3OM5HpQgaBRxvEjb2WUvJDLGdI5WcZoEoGpw0pVDllwoyABE+
        P7zUlv+EneOVl+jHjG84FnEMEi50KRw0colCnTJQYxR13u3u/Gf0NTPF0e5J8yKU
        oNStV5BxRLWh74P0KcaSPALtbvL5IdVe4wIfI/p9pB2AddriGV7VGBBJoX1n2WOQ
        R5BGgJJPHty2MpQCgs6nDM+n0V4c5L1lD0ooXLFucWBuePouaDW/P61w/Gpnw/BU
        qdCiN/ogKfCrOuuScpKqCSE3FRQeSTMWyBIHEa9RGBJq4gXq55Y7zWWRM4CJ3zXf
        0IzKCw9WK5XNiX0bFGbBAoIBAQDsRxBBrJMjYWjs/WJERVwBVJM83vxBSr4c5BDV
        TjuJkRnGtCvDmDcX/Zx7auLXGYFDKC7MJplUiDaowP30h7sLAYHlGARP/7ucJ6ND
        Nb44HxPUtsAP2MHkkkk9S3fxa7G31gACxJiMXb+XrF985tMZ4ODy40qI2qsKhXyF
        BUw9AHPxqZALeZlZkyS3T6HZbA+p6e5de3cnWdjqQvDtkUbK7vM/x+TuWWMbTLK/
        oE2VB+zhReZSNsEnAUZFckUJzaIUDIb5D8ClCIsrjvgaMDzwEojMZLM3HUi32htu
        Dydbuq20ViF4aZJ880ZLYJrp11El8d3WgWCOPcHVsgJKSkdVAoIBAQDn4MIt7ATD
        wtC2FP+IVCABCtvKxAj82YQQm2MPujUaJE/Mtceya8JExPTb8vYmtFnEoDTcS+9s
        sYvjsB4nmhTa7+Yq+E3AtV+AVeFERErcsX2S7hYass4HyPg82D/VBDDk+G6ufbhq
        qwi2zwScfKgTXVifq1BX2heoMw6AZnlpmPABcO/xvLzN3Wk9AeuYtqD+t40hXuMb
        59y/9VzLJq6RVGAWq2YfA43bZ8PtpN4qf/kP3rRf5ag9T/KN/4/dirN+Cnerkke8
        IsuDs7BFogBTbeuVsM5d4B9DsOBlV1mC25fqDuOQ1n505wk9HAAgWykI1fzDwvZt
        YcQ1r/5W0zTzAoIBAQC7TNomNZeuRFnZBEQRuqnkpBbT+jAd0hJC9MgjT5ECzHOS
        gODwfImwCusxKtoHicBebEwsqayCxjgOLm8imTY800UVRqSkhiVC9GkHrmLMOlaO
        GRDHfxy1BQHqBRlf1+9Zu9rmVtJW8zoeEhbf/Fr7+LhZ0rQTKMTN4mODT1/QO7ut
        pqz5a7uUtoA0kHvMz0zbdQXwNR+PojnB+q7ipHdqB2Hs/ZkNGO7nhTVtkrXtngq5
        yZ97LMyRDwGVq6/uxYPmQMf+R+5+5Pbt4LfsirDD3u1ymaE33471r4BvDrQ0kxeA
        DYca3RWy12ax+jLTjExXuBQTJxxTpcEylZobKibBAoIBABe+jUPUklxVe7fZiJ02
        OBzDNuSZlG4H/B0TPF6k68EkjMNirfNYU4llPcm0JH6sIzEeUqtoXzkbKT8EjuHx
        RkdxH3mw+Y1NRV1H7gxmjd/xkPFVzg+n1a84Zisc3dR7XGJmCjd2CkdqAjduFYPM
        xA1Plr6q9Uw5ughwSgDd/XrRvWn4Xam8cP0HujoUE0MNGIlc1GfhZpI5+QHzJzBq
        Yp/hKwHHRWrRm1onUwnnwxRJDIEShhf31XWJ1UWzMNE33c9/VOfNz+i1C3AOG3PV
        9gCVFfW7KDa2t5zf5Oqbuj/LKtA9/BGd1U81RV3rmxu1GguclgiZ01A6HbR9tCbB
        8/8CggEANb7Tbk8as4iBAP1M1zCSLlytCVbtSDob4sxpZCUmtE5EqFuFaTj0OgO9
        AGElTrDEnnnv5stTAzF71toeg8GyPK3Tup3hjtEJSOokRcNLhkbxPd98lcyx4bIF
        cYooOsCIKjh2sgKlHCXKHh+W5EVIt0u5S4fWu+9kh2dASRwlVBEsyBjm4IvxMY6o
        50OiWEUJBo1rqmNiEXy+eB4iBl/sGdrjRJHr1GP+1aTvNHS/di1c+z/iWTZTaZfb
        SzB2NIWxgm+riXdBzuw7uuPjrWCb5T8eQNgWH5zQiIWwYH/2C5amoM9+vSuVSPTU
        uBN156ID9PGy0ldRiJHcj6UDfySMgg==
        -----END PRIVATE KEY-----
