env:
  DOPPLER_PORT: 443

  prometheus:
  kubeStateMetrics:
    enabled: true

metrics:
  service:
    ingress:
      enabled: true
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-prod
      host: metrics.cap.suse.lab
  username: admin
  password: linux

cloudFoundry:
  apiEndpoint: https://api.cap.suse.lab
  uaaAdminClient: linux
  uaaAdminClientSecret: linux
