---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-sc
  finalizer: null
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
